export const CREATE_JOURNEY_PENDING = "CREATE_JOURNEY_PENDING"
export const CREATE_JOURNEY_SUCCESS = "CREATE_JOURNEY_SUCCESS"
export const CREATE_JOURNEY_ERROR = "CREATE_JOURNEY_ERROR"

export const DELETE_JOURNEY_PENDING = "DELETE_JOURNEY_PENDING"
export const DELETE_JOURNEY_SUCCESS = "DELETE_JOURNEY_SUCCESS"
export const DELETE_JOURNEY_ERROR = "DELETE_JOURNEY_ERROR"

export const GET_JOURNEY_PENDING = "GET_JOURNEY_PENDING"
export const GET_JOURNEY_SUCCESS = "GET_JOURNEY_SUCCESS"
export const GET_JOURNEY_ERROR = "GET_JOURNEY_ERROR"

export const GET_JOURNEYS_PENDING = "GET_JOURNEYS_PENDING"
export const GET_JOURNEYS_SUCCESS = "GET_JOURNEYS_SUCCESS"
export const GET_JOURNEYS_ERROR = "GET_JOURNEYS_ERROR"

export const UPDATE_JOURNEY_PENDING = "UPDATE_JOURNEY_PENDING"
export const UPDATE_JOURNEY_SUCCESS = "UPDATE_JOURNEY_SUCCESS"
export const UPDATE_JOURNEY_ERROR = "UPDATE_JOURNEY_ERROR"
