export const AUTHENTICATE_USER_PENDING = "AUTHENTICATE_USER_PENDING"
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS"
export const AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USER_ERROR"

export const CHECK_AUTH_PENDING = "CHECK_AUTH_PENDING"
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS"
export const CHECK_AUTH_ERROR = "CHECK_AUTH_ERROR"

export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_FAILURE"

export const SIGNOUT_USER_PENDING = "SIGNOUT_USER_PENDING"
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS"
export const SIGNOUT_USER_ERROR = "SIGNOUT_USER_ERROR"